### PR TITLE
when using ottca enrollment er->cert is null and segfaults on strlen

### PR DESCRIPTION
**Pull request by dovholuknf**
fixes ottca enrollment

build main - run the steps below - observe segfault
rebuild this branch - run the steps below - observe success and `head -5 clint.json` will show cert/key being paths in the identity file

#### steps:
```

# build ...
sampleEnroller="$(find . -type f -name "sample_enroll" -executable)"

# Define variables
caName="my-third-party-ca"
zitiUser="admin"
zitiPwd="admin"
zitiCtrl="localhost:1280"

# Login to Ziti
ziti edge login $zitiCtrl -u $zitiUser -p $zitiPwd -y

# Define the PKI root directory
zitiPkiRoot="${PWD}"

# Remove the directory recursively
rm -rf ${zitiPkiRoot}/pki/


# Create a CA
ziti pki create ca --pki-root "${zitiPkiRoot}" --ca-file "$caName"
rootCa=$(find . -name "${caName}.cert" -print -quit)

# Create the CA on the Ziti controller
ziti edge create ca "$caName" "$rootCa" --auth --ottca

# Get the verification token
verificationToken=$(ziti edge list cas -j | jq -r ".data | map(select(.name == \"$caName\"))[0].verificationToken")

# Create a client certificate
ziti pki create client --pki-root "${zitiPkiRoot}" --ca-name "$caName" --client-file "$verificationToken" --client-name "$verificationToken"
verificationCert=$(find . -name "${verificationToken}.cert" -print -quit)

# Verify the CA
ziti edge verify ca $caName --cert $verificationCert

# Create a new user
newUser="clint"
ziti edge delete identity "$newUser"
newUserName="clint-cn"
ziti pki create client --pki-root "${zitiPkiRoot}" --ca-name "$caName" --client-file "$newUser" --client-name "$newUserName"
newUserCert=$(find . -name "${newUser}.cert" -print -quit)
newUserKey=$(find . -name "${newUser}.key" -print -quit)
ziti edge create identity $newUser --external-id "$newUserName"

# Create an OTT enrollment for the new user
ziti edge create enrollment ottca $newUser $caName

# Get the OTTCA JWT
ottcajwt=$(ziti edge list identities "name contains \"$newUser\"" -j | jq -r '.data[].enrollment.ottca.jwt')

# Write the JWT to a file without a newline at the end
echo -n "$ottcajwt" > "${newUser}.jwt"

# Remove the JSON file
rm "${newUser}.json"

$sampleEnroller "${newUser}.jwt" "${newUser}.json" $newUserKey $newUserCert
```

### CODE REVIEW

**Comment by scareything** [comment]
should this be targeted to release-1.x?

**Comment by dovholuknf** [comment]
> should this be targeted to release-1.x?

Mmmm. Probably. Will release-1.x commits merge down to main? Would i do that?

**Comment by scareything** [comment]
> Mmmm. Probably. Will release-1.x commits merge down to main? Would i do that?

Yeah the merges are going from release-1.x to main. You could do it if you like, I just create a PR in GitHub from release-1.x to main.

**Review by scareything — APPROVED** [review]

**Comment by dovholuknf** [comment]
There's a bunch of changes. I'm gonna just dump the branch and rebranch - repr...

**Pull request closed without merging**
